### ISSUE TITLE
Remake piece graphics!

### ISSUE THREAD

**Issue by M-Blomqvist** [inda20plusplus/maltebl-chess#1]
As the solution with formatted unicode pieces didn't work the piece graphics are now just letters. That should change!

**Comment by leonardpauli** [comment]
![image](https://user-images.githubusercontent.com/1329834/94927385-7818f480-04c2-11eb-9e2f-eb38e7d68a60.png)
Graphics!

**Comment by leonardpauli** [comment]
Fixed, please see https://github.com/inda20plusplus/maltebl-chess/pull/6
